# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'takeform.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_Form(object):
    def setupUi(self, Form):
        if Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(859, 424)
        self.label_12 = QLabel(Form)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(40, 280, 55, 16))
        self.groupBox_2 = QGroupBox(Form)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(420, 190, 431, 221))
        self.label_13 = QLabel(self.groupBox_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 190, 71, 16))
        self.lineEdit = QLineEdit(self.groupBox_2)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(170, 190, 61, 24))
        self.label_2 = QLabel(self.groupBox_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 120, 71, 16))
        self.lineEdit_7 = QLineEdit(self.groupBox_2)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setEnabled(False)
        self.lineEdit_7.setGeometry(QRect(90, 40, 101, 24))
        self.label = QLabel(self.groupBox_2)
        self.label.setObjectName(u"label")
        self.label.setEnabled(True)
        self.label.setGeometry(QRect(10, 40, 55, 16))
        self.textEdit = QTextEdit(self.groupBox_2)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(90, 120, 331, 61))
        self.lineEdit_10 = QLineEdit(self.groupBox_2)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(90, 80, 113, 24))
        self.label_14 = QLabel(self.groupBox_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 80, 71, 16))
        self.lineEdit_42 = QLineEdit(self.groupBox_2)
        self.lineEdit_42.setObjectName(u"lineEdit_42")
        self.lineEdit_42.setEnabled(False)
        self.lineEdit_42.setGeometry(QRect(90, 190, 71, 24))
        self.pushButton_8 = QPushButton(self.groupBox_2)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(340, 30, 80, 41))
        self.pushButton_9 = QPushButton(self.groupBox_2)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(340, 75, 80, 31))
        self.groupBox = QGroupBox(Form)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 0, 841, 181))
        self.lineEdit_2 = QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QRect(230, 87, 191, 24))
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(130, 150, 91, 20))
        self.lineEdit_8 = QLineEdit(self.groupBox)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setEnabled(False)
        self.lineEdit_8.setGeometry(QRect(540, 63, 81, 24))
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(440, 33, 91, 20))
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(440, 63, 91, 20))
        self.lineEdit_5 = QLineEdit(self.groupBox)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setGeometry(QRect(540, 93, 291, 24))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(440, 123, 91, 20))
        self.lineEdit_3 = QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setGeometry(QRect(230, 120, 191, 24))
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(130, 90, 91, 20))
        self.lineEdit_6 = QLineEdit(self.groupBox)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_6.setGeometry(QRect(540, 123, 291, 24))
        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(130, 60, 91, 20))
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(130, 120, 91, 20))
        self.lineEdit_4 = QLineEdit(self.groupBox)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setGeometry(QRect(230, 150, 191, 24))
        self.label_10 = QLabel(self.groupBox)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 33, 101, 111))
        self.label_10.setFrameShape(QFrame.WinPanel)
        self.lineEdit_9 = QLineEdit(self.groupBox)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setEnabled(False)
        self.lineEdit_9.setGeometry(QRect(540, 33, 191, 24))
        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(440, 93, 91, 20))
        self.lineEdit_74 = QLineEdit(self.groupBox)
        self.lineEdit_74.setObjectName(u"lineEdit_74")
        self.lineEdit_74.setEnabled(False)
        self.lineEdit_74.setGeometry(QRect(230, 57, 191, 24))
        self.lineEdit_79 = QLineEdit(self.groupBox)
        self.lineEdit_79.setObjectName(u"lineEdit_79")
        self.lineEdit_79.setEnabled(False)
        self.lineEdit_79.setGeometry(QRect(629, 62, 81, 24))
        self.lineEdit_80 = QLineEdit(self.groupBox)
        self.lineEdit_80.setObjectName(u"lineEdit_80")
        self.lineEdit_80.setEnabled(False)
        self.lineEdit_80.setGeometry(QRect(540, 150, 291, 24))
        self.label_67 = QLabel(self.groupBox)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(440, 150, 91, 20))
        self.label_68 = QLabel(self.groupBox)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(130, 30, 91, 20))
        self.lineEdit_81 = QLineEdit(self.groupBox)
        self.lineEdit_81.setObjectName(u"lineEdit_81")
        self.lineEdit_81.setEnabled(False)
        self.lineEdit_81.setGeometry(QRect(230, 27, 61, 24))
        self.groupBox_3 = QGroupBox(Form)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 190, 401, 221))
        self.lineEdit_36 = QLineEdit(self.groupBox_3)
        self.lineEdit_36.setObjectName(u"lineEdit_36")
        self.lineEdit_36.setEnabled(False)
        self.lineEdit_36.setGeometry(QRect(90, 120, 131, 24))
        self.lineEdit_35 = QLineEdit(self.groupBox_3)
        self.lineEdit_35.setObjectName(u"lineEdit_35")
        self.lineEdit_35.setEnabled(False)
        self.lineEdit_35.setGeometry(QRect(90, 87, 131, 24))
        self.label_23 = QLabel(self.groupBox_3)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 90, 71, 20))
        self.label_23.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_39 = QLabel(self.groupBox_3)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(10, 120, 71, 20))
        self.label_39.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_40 = QLabel(self.groupBox_3)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(10, 150, 71, 20))
        self.label_40.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_37 = QLineEdit(self.groupBox_3)
        self.lineEdit_37.setObjectName(u"lineEdit_37")
        self.lineEdit_37.setEnabled(False)
        self.lineEdit_37.setGeometry(QRect(90, 150, 131, 24))
        self.lineEdit_38 = QLineEdit(self.groupBox_3)
        self.lineEdit_38.setObjectName(u"lineEdit_38")
        self.lineEdit_38.setEnabled(False)
        self.lineEdit_38.setGeometry(QRect(230, 86, 61, 24))
        self.lineEdit_39 = QLineEdit(self.groupBox_3)
        self.lineEdit_39.setObjectName(u"lineEdit_39")
        self.lineEdit_39.setEnabled(False)
        self.lineEdit_39.setGeometry(QRect(230, 120, 61, 24))
        self.lineEdit_40 = QLineEdit(self.groupBox_3)
        self.lineEdit_40.setObjectName(u"lineEdit_40")
        self.lineEdit_40.setEnabled(False)
        self.lineEdit_40.setGeometry(QRect(230, 150, 61, 24))
        self.lineEdit_77 = QLineEdit(self.groupBox_3)
        self.lineEdit_77.setObjectName(u"lineEdit_77")
        self.lineEdit_77.setEnabled(False)
        self.lineEdit_77.setGeometry(QRect(90, 54, 301, 24))
        self.lineEdit_77.setEchoMode(QLineEdit.Normal)
        self.label_65 = QLabel(self.groupBox_3)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(10, 54, 71, 20))
        self.label_66 = QLabel(self.groupBox_3)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(10, 20, 71, 20))
        self.lineEdit_76 = QLineEdit(self.groupBox_3)
        self.lineEdit_76.setObjectName(u"lineEdit_76")
        self.lineEdit_76.setEnabled(False)
        self.lineEdit_76.setGeometry(QRect(90, 24, 121, 24))
        self.lineEdit_76.setEchoMode(QLineEdit.Normal)
        self.lineEdit_75 = QLineEdit(self.groupBox_3)
        self.lineEdit_75.setObjectName(u"lineEdit_75")
        self.lineEdit_75.setEnabled(False)
        self.lineEdit_75.setGeometry(QRect(329, 24, 61, 24))
        self.lineEdit_75.setEchoMode(QLineEdit.Normal)
        self.label_64 = QLabel(self.groupBox_3)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(308, 26, 20, 20))
        QWidget.setTabOrder(self.lineEdit_10, self.textEdit)
        QWidget.setTabOrder(self.textEdit, self.lineEdit)
        QWidget.setTabOrder(self.lineEdit, self.pushButton_8)
        QWidget.setTabOrder(self.pushButton_8, self.pushButton_9)
        QWidget.setTabOrder(self.pushButton_9, self.lineEdit_7)
        QWidget.setTabOrder(self.lineEdit_7, self.lineEdit_42)
        QWidget.setTabOrder(self.lineEdit_42, self.lineEdit_2)
        QWidget.setTabOrder(self.lineEdit_2, self.lineEdit_8)
        QWidget.setTabOrder(self.lineEdit_8, self.lineEdit_5)
        QWidget.setTabOrder(self.lineEdit_5, self.lineEdit_3)
        QWidget.setTabOrder(self.lineEdit_3, self.lineEdit_6)
        QWidget.setTabOrder(self.lineEdit_6, self.lineEdit_4)
        QWidget.setTabOrder(self.lineEdit_4, self.lineEdit_9)
        QWidget.setTabOrder(self.lineEdit_9, self.lineEdit_74)
        QWidget.setTabOrder(self.lineEdit_74, self.lineEdit_79)
        QWidget.setTabOrder(self.lineEdit_79, self.lineEdit_80)
        QWidget.setTabOrder(self.lineEdit_80, self.lineEdit_81)
        QWidget.setTabOrder(self.lineEdit_81, self.lineEdit_36)
        QWidget.setTabOrder(self.lineEdit_36, self.lineEdit_35)
        QWidget.setTabOrder(self.lineEdit_35, self.lineEdit_37)
        QWidget.setTabOrder(self.lineEdit_37, self.lineEdit_38)
        QWidget.setTabOrder(self.lineEdit_38, self.lineEdit_39)
        QWidget.setTabOrder(self.lineEdit_39, self.lineEdit_40)
        QWidget.setTabOrder(self.lineEdit_40, self.lineEdit_77)
        QWidget.setTabOrder(self.lineEdit_77, self.lineEdit_76)
        QWidget.setTabOrder(self.lineEdit_76, self.lineEdit_75)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label_12.setText("")
        self.groupBox_2.setTitle(QCoreApplication.translate("Form", u"Please fill the blanks for your using with reason", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"Quantity", None))
        self.lineEdit.setText("")
        self.lineEdit.setPlaceholderText(QCoreApplication.translate("Form", u"used", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"Description", None))
        self.label.setText(QCoreApplication.translate("Form", u"User ID", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"Your Name", None))
        self.lineEdit_42.setText(QCoreApplication.translate("Form", u"Current", None))
        self.lineEdit_42.setPlaceholderText(QCoreApplication.translate("Form", u"Number", None))
        self.pushButton_8.setText(QCoreApplication.translate("Form", u"TAKE", None))
        self.pushButton_9.setText(QCoreApplication.translate("Form", u"CANCEL", None))
        self.groupBox.setTitle(QCoreApplication.translate("Form", u"Properties", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"Code-2", None))
        self.lineEdit_8.setPlaceholderText(QCoreApplication.translate("Form", u"Price", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"Manufacture", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"Price", None))
        self.lineEdit_5.setPlaceholderText(QCoreApplication.translate("Form", u"Property -1", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"Property -2", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"Name", None))
        self.lineEdit_6.setPlaceholderText(QCoreApplication.translate("Form", u"Property -2", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"Material Type", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"Code-1", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"image", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"Property -1", None))
        self.lineEdit_79.setPlaceholderText(QCoreApplication.translate("Form", u"Currency", None))
        self.lineEdit_80.setPlaceholderText(QCoreApplication.translate("Form", u"Record Date", None))
        self.label_67.setText(QCoreApplication.translate("Form", u"Record Date", None))
        self.label_68.setText(QCoreApplication.translate("Form", u"ID", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Form", u"Location", None))
        self.lineEdit_36.setPlaceholderText(QCoreApplication.translate("Form", u"Code", None))
        self.lineEdit_35.setText("")
        self.lineEdit_35.setPlaceholderText(QCoreApplication.translate("Form", u"Number", None))
        self.label_23.setText(QCoreApplication.translate("Form", u"Room", None))
        self.label_39.setText(QCoreApplication.translate("Form", u"Cabinet", None))
        self.label_40.setText(QCoreApplication.translate("Form", u"Shelf", None))
        self.lineEdit_37.setPlaceholderText(QCoreApplication.translate("Form", u"Code", None))
        self.lineEdit_38.setPlaceholderText(QCoreApplication.translate("Form", u"ID", None))
        self.lineEdit_39.setPlaceholderText(QCoreApplication.translate("Form", u"ID", None))
        self.lineEdit_40.setPlaceholderText(QCoreApplication.translate("Form", u"ID", None))
        self.lineEdit_77.setPlaceholderText(QCoreApplication.translate("Form", u"Final Stock Code", None))
        self.label_65.setText(QCoreApplication.translate("Form", u"Final Code", None))
        self.label_66.setText(QCoreApplication.translate("Form", u"Stock Code", None))
        self.lineEdit_76.setPlaceholderText(QCoreApplication.translate("Form", u"Stock Code", None))
        self.lineEdit_75.setText("")
        self.lineEdit_75.setPlaceholderText(QCoreApplication.translate("Form", u"ID", None))
        self.label_64.setText(QCoreApplication.translate("Form", u"ID", None))
    # retranslateUi

